name: bc-monitor
channels:
  - conda-forge
dependencies:
  - python = 3.9

# CORE:
  - aiohttp
  - fsspec
  - netCDF4
  - scipy
  - xarray
  - argopy

# UTIL:
  - gsw
  - tqdm

# STAT:
  - dask
  - dask-ml
  - distributed
  - scikit-learn
  - xhistogram

# PLOT:
  - cartopy
  - ipykernel
  - matplotlib
  - regionmask
  - seaborn

# DEV:
  - numpy
  - pandas
  - pip

# PIP:
  - pip:
      - git+https://github.com/obidam/pyxpcm.git@master
      - copernicusmarine>=1.0<=2.0
